export { decodeLibraryV3, encodeLibraryV3 } from "./canonicalEncoding";
export {
	LIBRARY_V3_EXTENSIONS_SCHEMA_VERSION,
	LIBRARY_V3_SCHEMA_VERSION,
	MAX_AUTHOR_BYTES,
	MAX_COLLECTION_ID_BYTES,
	MAX_CONTENT_TEXT_BYTES,
	MAX_CUSTOM_PLAYLISTS,
	MAX_DESCRIPTION_TEXT_BYTES,
	MAX_DOWNLOADS_PER_EPISODE,
	MAX_EPISODES,
	MAX_FEEDS,
	MAX_ICON_BYTES,
	MAX_LIBRARY_V3_BYTES,
	MAX_LOCAL_ASSETS,
	MAX_PLAYLIST_EPISODE_REFERENCES,
	MAX_PLAYLIST_NAME_BYTES,
	MAX_POD_NOTE_ENTRIES,
	MAX_PROGRESS_ENTRIES,
	MAX_TITLE_BYTES,
	MAX_TOTAL_EPISODE_REFERENCES,
	MAX_TOTAL_TEXT_BYTES,
	MAX_VAULT_PATH_BYTES,
	LibraryV3ValidationError,
	type DownloadAssetV3,
	type DownloadMapV3,
	type EpisodeMapV3,
	type EpisodeProgressV3,
	type FeedMapV3,
	type LibraryEpisodeV3,
	type LibraryExtensionsV1,
	type LibraryFeedV3,
	type LibraryPlaylistV3,
	type LibraryV3,
	type LocalAssetMapV3,
	type LocalAssetV3,
	type LocalFeedV3,
	type PodNoteMapV3,
	type PodNoteV3,
	type ProgressMapV3,
	type RemoteFeedV3,
} from "./model";
export { validateLibraryV3 } from "./validateLibrary";
export { portableVaultPathOwnershipKey } from "./scalars";
