import { builtinModules } from "node:module";
import path from "node:path";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import { defineConfig } from "vite";
import { createBuildArtifactPlugin } from "./scripts/build-artifacts";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

const externalDeps = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/closebrackets",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/comment",
	"@codemirror/fold",
	"@codemirror/gutter",
	"@codemirror/highlight",
	"@codemirror/history",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/matchbrackets",
	"@codemirror/panel",
	"@codemirror/rangeset",
	"@codemirror/rectangular-selection",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/stream-parser",
	"@codemirror/text",
	"@codemirror/tooltip",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
];

const builtinExternals = builtinModules.filter((moduleName) => !moduleName.startsWith("_"));

const external = [
	...externalDeps,
	...builtinExternals,
	...builtinExternals.map((moduleName) => `node:${moduleName}`),
];

export default defineConfig(({ mode }) => {
	const isProd = mode === "production";
	const outDir = path.resolve(__dirname, "build");

	return {
		plugins: [
			svelte({
				compilerOptions: { css: "injected" },
			}),
			createBuildArtifactPlugin({ isProduction: isProd, outDir, rootDir: __dirname }),
		],
		resolve: {
			alias: {
				src: path.resolve(__dirname, "src"),
			},
			conditions: ["browser"],
		},
		build: {
			lib: {
				entry: path.resolve(__dirname, "src/main.ts"),
				formats: ["cjs"],
				fileName: () => "main.js",
			},
			target: "es2020",
			outDir,
			emptyOutDir: true,
			sourcemap: !isProd,
			minify: false,
			rollupOptions: {
				external,
				output: {
					entryFileNames: "main.js",
					codeSplitting: false,
					exports: "auto",
					banner,
					// Vite 8 dropped the esbuild transform (and with it
					// esbuild.drop), so prod minification and console
					// stripping both move to rolldown's oxc minifier.
					minify: isProd
						? { compress: { dropConsole: true }, mangle: true, codegen: true }
						: false,
				},
			},
		},
	};
});
