import fs from "node:fs";
import { builtinModules } from "node:module";
import path from "node:path";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import sveltePreprocess from "svelte-preprocess";
import { defineConfig } from "vite";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
If you want to view the source, please visit the GitHub repository of this plugin.
*/
`;

const externalDeps = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/closebrackets",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/comment",
	"@codemirror/fold",
	"@codemirror/gutter",
	"@codemirror/highlight",
	"@codemirror/history",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/matchbrackets",
	"@codemirror/panel",
	"@codemirror/rangeset",
	"@codemirror/rectangular-selection",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/stream-parser",
	"@codemirror/text",
	"@codemirror/tooltip",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
];

const builtinExternals = builtinModules.filter(
	(moduleName) => !moduleName.startsWith("_"),
);

const external = [
	...externalDeps,
	...builtinExternals,
	...builtinExternals.map((moduleName) => `node:${moduleName}`),
];

export default defineConfig(({ mode }) => {
	const isProd = mode === "production";
	const outDir = isProd ? "." : "build";

	const devSymlinkPlugin = () => ({
		name: "podnotes-dev-symlink",
		writeBundle() {
			if (isProd) return;

			const ensureSymlink = (from: string, to: string) => {
				try {
					const stat = fs.lstatSync(to);
					if (stat.isSymbolicLink() || stat.isFile()) {
						fs.unlinkSync(to);
					}
				} catch {
					// target does not exist – that's fine
				}

				fs.symlinkSync(from, to);
			};

			const builtMain = path.resolve(__dirname, outDir, "main.js");
			const builtMap = path.resolve(__dirname, outDir, "main.js.map");
			const rootMain = path.resolve(__dirname, "main.js");
			const rootMap = path.resolve(__dirname, "main.js.map");

			if (fs.existsSync(builtMain)) ensureSymlink(builtMain, rootMain);
			if (fs.existsSync(builtMap)) ensureSymlink(builtMap, rootMap);
		},
	});

	return {
		plugins: [
			svelte({
				preprocess: sveltePreprocess(),
				compilerOptions: { css: "injected" },
			}),
			devSymlinkPlugin(),
		],
		resolve: {
			alias: {
				src: path.resolve(__dirname, "src"),
			},
			conditions: ["browser"],
		},
		build: {
			lib: {
				entry: path.resolve(__dirname, "src/main.ts"),
				formats: ["cjs"],
				fileName: () => "main.js",
			},
			target: "es2020",
			outDir,
			emptyOutDir: false,
			sourcemap: !isProd,
			minify: isProd ? "esbuild" : false,
			rollupOptions: {
				external,
				output: {
					entryFileNames: "main.js",
					inlineDynamicImports: true,
					exports: "auto",
					banner,
				},
			},
		},
		esbuild: isProd ? { drop: ["console"] } : {},
	};
});
