name: Feature request
description: Suggest an improvement to PodNotes
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What would you like PodNotes to do?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you have tried
