name: Documentation
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "docs/**"
      - ".github/workflows/documentation.yml"
      - "wrangler.jsonc"
      - "package.json"
      - ".nvmrc"
  push:
    branches:
      - "master"
    paths:
      - "docs/**"
      - ".github/workflows/documentation.yml"
      - "wrangler.jsonc"
      - "package.json"
      - ".nvmrc"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "docs/package-lock.json"

      - name: Build documentation
        run: npm run docs:build
